// CEM N°83 - Villa Regina, Río Negro
// Ciclo Lectivo 2026
// Generado automáticamente desde planilla Excel

const estudiantes = [

  // ── MÓDULO 1 ─────────────────────────────────────────
  // 1° Año - División 1
  { nombre: "ACEITON, Sara Noemi",                      curso: "1", division: "1", modulo: "1" },
  { nombre: "ANEMOGEANIS, Demian Ezequiel",             curso: "1", division: "1", modulo: "1" },
  { nombre: "DEL VALLE, Abril",                         curso: "1", division: "1", modulo: "1" },
  { nombre: "FERNANDEZ HERNANDEZ, Cristina Magdalena",  curso: "1", division: "1", modulo: "1" },
  { nombre: "FIGUEROA, Agustina Abigail",               curso: "1", division: "1", modulo: "1" },
  { nombre: "GARRIDO, Gloria Magdalena",                curso: "1", division: "1", modulo: "1" },
  { nombre: "INOSTROZA, Marcela Sheyla",                curso: "1", division: "1", modulo: "1" },
  { nombre: "LUCERO, Enzo Alejandro",                   curso: "1", division: "1", modulo: "1" },
  { nombre: "MARIPIL, Milagros",                        curso: "1", division: "1", modulo: "1" },
  { nombre: "MENDOZA, Amir",                            curso: "1", division: "1", modulo: "1" },
  { nombre: "MORA, Flor Genoveva Elizabeth",            curso: "1", division: "1", modulo: "1" },
  { nombre: "MORA ESTIVE, Saskia Samira",               curso: "1", division: "1", modulo: "1" },
  { nombre: "MUÑOZ, Thiago Natanael",                   curso: "1", division: "1", modulo: "1" },
  { nombre: "NEIRA, Jonathan Rodrigo",                  curso: "1", division: "1", modulo: "1" },
  { nombre: "OLESKIW, Angeles",                         curso: "1", division: "1", modulo: "1" },
  { nombre: "PAREDES, Gonzalo Andres",                  curso: "1", division: "1", modulo: "1" },
  { nombre: "PAREDES, Nair Javier",                     curso: "1", division: "1", modulo: "1" },
  { nombre: "RETAMAL, Patricia Marina Belén",           curso: "1", division: "1", modulo: "1" },
  { nombre: "SANCHEZ, Danisa Mariel",                   curso: "1", division: "1", modulo: "1" },
  { nombre: "TRAIPE, Lucas Nicolas",                    curso: "1", division: "1", modulo: "1" },

  // 1° Año - División 2
  { nombre: "ALVEAL, Evelyn Daiana",                    curso: "1", division: "2", modulo: "1" },
  { nombre: "ARIAS TEMPERINI, Melisa Macarena",         curso: "1", division: "2", modulo: "1" },
  { nombre: "BALLE CARDENAS, Jeremias Joaquin",         curso: "1", division: "2", modulo: "1" },
  { nombre: "CARRAZCO, Jesica Vanina",                  curso: "1", division: "2", modulo: "1" },
  { nombre: "CORDOBA, Melanie Ariana",                  curso: "1", division: "2", modulo: "1" },
  { nombre: "FIGUEROA, Mía Julieta",                    curso: "1", division: "2", modulo: "1" },
  { nombre: "JUAREZ, Santiago",                         curso: "1", division: "2", modulo: "1" },
  { nombre: "LEDEZMA, Yanela",                          curso: "1", division: "2", modulo: "1" },
  { nombre: "MANRIQUE, Micaela Belen",                  curso: "1", division: "2", modulo: "1" },
  { nombre: "MARQUEZ, Juliana Abril",                   curso: "1", division: "2", modulo: "1" },
  { nombre: "MATUS, Abril Ayelén",                      curso: "1", division: "2", modulo: "1" },
  { nombre: "MATUS, Jessica",                           curso: "1", division: "2", modulo: "1" },
  { nombre: "MORA, Gabriel Victor Hugo",                curso: "1", division: "2", modulo: "1" },
  { nombre: "MUÑOZ, Chiara del Rosario",                curso: "1", division: "2", modulo: "1" },
  { nombre: "MUÑOZ, Kiara",                             curso: "1", division: "2", modulo: "1" },
  { nombre: "PACHECO, Ariel Emiliano",                  curso: "1", division: "2", modulo: "1" },
  { nombre: "PARRA, Evelyn",                            curso: "1", division: "2", modulo: "1" },
  { nombre: "PINTO, Gabriela Michelle",                 curso: "1", division: "2", modulo: "1" },
  { nombre: "VILLEGAS, Erick Leonel Hernan",            curso: "1", division: "2", modulo: "1" },

  // 1° Año - División 3
  { nombre: "ACUÑA, Macarena Daniela",                  curso: "1", division: "3", modulo: "1" },
  { nombre: "BUSTOS, Saira Laura",                      curso: "1", division: "3", modulo: "1" },
  { nombre: "CHEUQUEPAN, Carmen",                       curso: "1", division: "3", modulo: "1" },
  { nombre: "CHEUQUETA, Domingo Omar",                  curso: "1", division: "3", modulo: "1" },
  { nombre: "CONTI, Jonathan",                          curso: "1", division: "3", modulo: "1" },
  { nombre: "CONTRERAS, Marcela Fabiana",               curso: "1", division: "3", modulo: "1" },
  { nombre: "CONTRERAS, Vanesa Isabel",                 curso: "1", division: "3", modulo: "1" },
  { nombre: "FERNANDEZ, Elvia Vanina",                  curso: "1", division: "3", modulo: "1" },
  { nombre: "FERNANDEZ, Fredy Alberto",                 curso: "1", division: "3", modulo: "1" },
  { nombre: "GONZALEZ FRANCHI, Lucylena",               curso: "1", division: "3", modulo: "1" },
  { nombre: "JARA, Alicia Ines",                        curso: "1", division: "3", modulo: "1" },
  { nombre: "JARAMILLO, Ayelen Beatriz",                curso: "1", division: "3", modulo: "1" },
  { nombre: "JARAMILLO, Priscila Monica",               curso: "1", division: "3", modulo: "1" },
  { nombre: "RUBIO, Elda Alicia",                       curso: "1", division: "3", modulo: "1" },
  { nombre: "SANCHEZ, Maria Cristina",                  curso: "1", division: "3", modulo: "1" },
  { nombre: "SUBIABRE, Valeria Belen",                  curso: "1", division: "3", modulo: "1" },

  // ── MÓDULO 2 ─────────────────────────────────────────
  // 2° Año - División 1
  { nombre: "ALARCON MALDONADO, Dalma",                 curso: "2", division: "1", modulo: "2" },
  { nombre: "ALBORNOZ, José Carlos",                    curso: "2", division: "1", modulo: "2" },
  { nombre: "ARIAS TEMPERINI, Maria Eugenia",           curso: "2", division: "1", modulo: "2" },
  { nombre: "CHANIQUE, Valentín Tomás",                 curso: "2", division: "1", modulo: "2" },
  { nombre: "ESCALONA, Cintia Yanina",                  curso: "2", division: "1", modulo: "2" },
  { nombre: "FUENSALIDA, Santiago",                     curso: "2", division: "1", modulo: "2" },
  { nombre: "GUERRERO PAINEMILLA, Mailen Solange",      curso: "2", division: "1", modulo: "2" },
  { nombre: "MANSILLA SOSA, Lisandro Isaias",           curso: "2", division: "1", modulo: "2" },
  { nombre: "MUÑOZ, Gabriela",                          curso: "2", division: "1", modulo: "2" },
  { nombre: "MUÑOZ, Graciela Roxana",                   curso: "2", division: "1", modulo: "2" },
  { nombre: "MUÑOZ, Lucila",                            curso: "2", division: "1", modulo: "2" },
  { nombre: "MUÑOZ, Melani Marite",                     curso: "2", division: "1", modulo: "2" },
  { nombre: "QUIJON, Roxana Mariel",                    curso: "2", division: "1", modulo: "2" },

  // 2° Año - División 2
  { nombre: "ALBORNOZ, Brisa Noemi",                    curso: "2", division: "2", modulo: "2" },
  { nombre: "ARRUZA, Thiago Lautaro",                   curso: "2", division: "2", modulo: "2" },
  { nombre: "FERNANDEZ, Luisana",                       curso: "2", division: "2", modulo: "2" },
  { nombre: "FUENZALIDA, Santiago",                     curso: "2", division: "2", modulo: "2" },
  { nombre: "LARA, Adrian Abel",                        curso: "2", division: "2", modulo: "2" },
  { nombre: "MATUS, Cintia",                            curso: "2", division: "2", modulo: "2" },
  { nombre: "MELIQUEO, Victoria Catalina",              curso: "2", division: "2", modulo: "2" },
  { nombre: "OLATE, Marilu de los Angeles",             curso: "2", division: "2", modulo: "2" },
  { nombre: "QUIROGA, Nerea Celeste",                   curso: "2", division: "2", modulo: "2" },
  { nombre: "QUIROGA, Rocio Ayelen",                    curso: "2", division: "2", modulo: "2" },
  { nombre: "SECO, Juan Cruz",                          curso: "2", division: "2", modulo: "2" },
  { nombre: "SILVA, Camila Belen",                      curso: "2", division: "2", modulo: "2" },
  { nombre: "TRIVIÑO, Mayra Yael Andrea",               curso: "2", division: "2", modulo: "2" },
  { nombre: "VEJAR, Kevin",                             curso: "2", division: "2", modulo: "2" },

  // 2° Año - División 3
  { nombre: "AGUAYSOL, Fernando Gabriel",               curso: "2", division: "3", modulo: "2" },
  { nombre: "ALMEYRA, Morena Nahir",                    curso: "2", division: "3", modulo: "2" },
  { nombre: "BURGOS, Analia",                           curso: "2", division: "3", modulo: "2" },
  { nombre: "CATRIQUIR, Yamila Ailen",                  curso: "2", division: "3", modulo: "2" },
  { nombre: "CONTRERAS, Claudia Beatriz",               curso: "2", division: "3", modulo: "2" },
  { nombre: "HUENCHUMIL, Julia Ester",                  curso: "2", division: "3", modulo: "2" },
  { nombre: "HUENTECOL, Guadalupe",                     curso: "2", division: "3", modulo: "2" },
  { nombre: "MORA, Gabriel Victor Hugo",                curso: "2", division: "3", modulo: "2" },
  { nombre: "MUÑOZ, Miguel Angel",                      curso: "2", division: "3", modulo: "2" },
  { nombre: "SEPULVEDA, Marianela",                     curso: "2", division: "3", modulo: "2" },
  { nombre: "SORIA, Mayra Amanda",                      curso: "2", division: "3", modulo: "2" },
  { nombre: "VERGARA, Franco Aaron",                    curso: "2", division: "3", modulo: "2" },

  // ── MÓDULO 3 ─────────────────────────────────────────
  // 3° Año - División 1
  { nombre: "ABARZO, Lucas",                            curso: "3", division: "1", modulo: "3" },
  { nombre: "CANALES, Mateo Nahuel",                    curso: "3", division: "1", modulo: "3" },
  { nombre: "CASTILLO, Sergio Santiago",                curso: "3", division: "1", modulo: "3" },
  { nombre: "CESAR REBERT, Marcos Damian",              curso: "3", division: "1", modulo: "3" },
  { nombre: "CHIRINO, Alexander Gabriel",               curso: "3", division: "1", modulo: "3" },
  { nombre: "COLICHEO PINTO, Betsabe",                  curso: "3", division: "1", modulo: "3" },
  { nombre: "FLORES, Leonela Mabel",                    curso: "3", division: "1", modulo: "3" },
  { nombre: "HERRERA, Juliana Agostina",                curso: "3", division: "1", modulo: "3" },
  { nombre: "LONCON, Maximiliano Sergio Adrian",        curso: "3", division: "1", modulo: "3" },
  { nombre: "MARQUEZ, Roberto Gaston",                  curso: "3", division: "1", modulo: "3" },
  { nombre: "NAVARRETE, Carla Rocío",                   curso: "3", division: "1", modulo: "3" },
  { nombre: "VAZQUEZ GARCIA, Brian Eduardo",            curso: "3", division: "1", modulo: "3" },
  { nombre: "VERDECCHIA, Micaela Aurora",               curso: "3", division: "1", modulo: "3" },
  { nombre: "VERDECCHIA, Milagros del Valle",           curso: "3", division: "1", modulo: "3" },
  { nombre: "VERDECCHIA, Nayla Sharon del Carmen",      curso: "3", division: "1", modulo: "3" },

  // 3° Año - División 2
  { nombre: "CERDA, Micaela",                           curso: "3", division: "2", modulo: "3" },
  { nombre: "DELGADO, Cristina Mariana",                curso: "3", division: "2", modulo: "3" },
  { nombre: "FICA, Tamara",                             curso: "3", division: "2", modulo: "3" },
  { nombre: "GAVILANI, Marcela Fernanda",               curso: "3", division: "2", modulo: "3" },
  { nombre: "HUENCHU, Evelyn Luna",                     curso: "3", division: "2", modulo: "3" },
  { nombre: "INOSTROZA, Oriana",                        curso: "3", division: "2", modulo: "3" },
  { nombre: "INOSTROZA, Samira Oriana",                 curso: "3", division: "2", modulo: "3" },
  { nombre: "JEREZ, Rocio Belen",                       curso: "3", division: "2", modulo: "3" },
  { nombre: "LOIZZO, Yamila",                           curso: "3", division: "2", modulo: "3" },
  { nombre: "MIANI, Elias Gustavo",                     curso: "3", division: "2", modulo: "3" },
  { nombre: "MIANI, Matias Ariel",                      curso: "3", division: "2", modulo: "3" },
  { nombre: "MONCADA, Franco",                          curso: "3", division: "2", modulo: "3" },
  { nombre: "PETRIS, Gianella Jazmin",                  curso: "3", division: "2", modulo: "3" },
  { nombre: "QUIROZ, Melanie",                          curso: "3", division: "2", modulo: "3" },
  { nombre: "QUIROZ, Micaela",                          curso: "3", division: "2", modulo: "3" },
  { nombre: "SALOMON, Nadia Alejandra",                 curso: "3", division: "2", modulo: "3" },
  { nombre: "SANZANA, Morena Aymara",                   curso: "3", division: "2", modulo: "3" },
  { nombre: "SCHMIDT, Maria de los Angeles",            curso: "3", division: "2", modulo: "3" },
  { nombre: "SILISQUE, Cristina",                       curso: "3", division: "2", modulo: "3" },
  { nombre: "SILVA, Karina Daniela",                    curso: "3", division: "2", modulo: "3" },
  { nombre: "VILLEGAS, Oscar Alejandro",                curso: "3", division: "2", modulo: "3" },

  // 3° Año - División 3
  { nombre: "CANIO, Lorena Margot",                     curso: "3", division: "3", modulo: "3" },
  { nombre: "CAÑUECO, Alicia",                          curso: "3", division: "3", modulo: "3" },
  { nombre: "CAÑUQUEO FERNANDEZ, Alicia Monica",        curso: "3", division: "3", modulo: "3" },
  { nombre: "CARDENAS, Georgina Paola",                 curso: "3", division: "3", modulo: "3" },
  { nombre: "CARRASCO, Carolina Gisella",               curso: "3", division: "3", modulo: "3" },
  { nombre: "CHANQUEO, Alicia",                         curso: "3", division: "3", modulo: "3" },
  { nombre: "CONTRERAS, Claudia",                       curso: "3", division: "3", modulo: "3" },
  { nombre: "FIGUEROA, Daiana Marilyn",                 curso: "3", division: "3", modulo: "3" },
  { nombre: "GARRIDO, Veronica Vanesa",                 curso: "3", division: "3", modulo: "3" },
  { nombre: "JARA, Maria Nieves",                       curso: "3", division: "3", modulo: "3" },
  { nombre: "MAIDANA, Milena Aylen",                    curso: "3", division: "3", modulo: "3" },
  { nombre: "MARILAF, Romina Alejandra",                curso: "3", division: "3", modulo: "3" },
  { nombre: "MONTEROS, Pablo Nicolas",                  curso: "3", division: "3", modulo: "3" },
  { nombre: "MORALES, Claudia Graciela",                curso: "3", division: "3", modulo: "3" },
  { nombre: "MOREIRA, María Cristina",                  curso: "3", division: "3", modulo: "3" },
  { nombre: "PINILLA, Rosana Beatriz",                  curso: "3", division: "3", modulo: "3" },
  { nombre: "TIZNADO, Graciela Marysol",                curso: "3", division: "3", modulo: "3" },
  { nombre: "TRIPAILAO, Erica Natalia",                 curso: "3", division: "3", modulo: "3" },

];
